name: shell commands

on:
  - push

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWSKEYID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWSSECRETKEY }}
 

jobs:
  test-pwd:
    runs-on: windows-latest
    steps:
      - name: Check linux pw directory
        run: |
          ls /
          pwd

  terraform-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set-up terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.9
      - name: Terraform Init
        run: terraform init
      - name: Terraform Validate
        run: terraform validate
      - name: Terraform Plan
        run: terraform plan
      - name: release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Terraform Apply
      #   run: terraform apply --auto-approve
      # - name: Terraform Destroy
      #   run: terraform destroy --auto-approve
      
     
  
